Use explicit scoping
Since last commit, catalog cannot be computed.  This seems to be linked
to a scopping error:

  Line: 7
  Detail: undefined method `each' for nil:NilClass